allow-shorthand: false

inherits:
  - strictness_veryhigh

ignore-patterns:
  - ^setup.py$

pylint:
  disable:
    - too-few-public-methods
    - too-many-public-methods
    - deprecated-lambda
    - bad-builtin
    - star-args
    - global-statement
    - assignment-from-none
    - unused-format-string-key
    - W5103

  options:
    max-locals: 15
    max-returns: 6
    max-branches: 15
    max-statements: 60
    min-public-methods: 1
    max-public-methods: 20
    max-line-length: 99
    ignored-modules: bpy,parameterized

pep8:
  options:
    max-line-length: 99
  disable:
    - N811
    - N812
    - N813
    - N814
    - E226

pyroma:
  disable:
    - PYR15
    - PYR18
    - PYR17

pep257:
  disable:
    - D400
    - D401
