# env setup
language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests and upload coverage
script:
  - python -m unittest discover -v
  - coverage run --source=. -m unittest discover
  - coverage report
  - coverage xml
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
